resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- argocd-projects.yaml
- ingressroute.yaml
- repo-k3s.yaml
- parentapp.yaml
patches:
  - path: argocd-cmd-params-cm-patch.yaml
  - target:
      kind: ConfigMap
      name: argocd-rbac-cm
      namespace: argocd
    patch: |-
      - op: add
        path: /data/scopes
        value: '[permissionNames]'
      - op: add
        path: /data/policy.csv
        value: |
          g, admin, role:admin
          g, editor, role:editor
          g, viewer, role:readonly