apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    traefik: false
    ingress: true 
  settings.yaml: |
    title: "home.thomason.nu"
    description: "A central hub for all my services and tools."
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - Tools:
      - AI Open WebUI:
            href: "https://ai.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: AI Chat
            icon: sh-open-webui.svg
      - Planka:
            href: "https://plan.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: Planning Board
            icon: sh-planka.svg
      - Grafana:
            href: "https://grafana.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: Dashboards
            icon: sh-grafana.svg
      - Container Registry:
            href: "https://dockerui.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: Container Registry
            icon: sh-docker.svg
    - Home Automation:
        - Home Assistant:
            href: "https://assistant.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: Home Automation Hub
            icon: sh-home-assistant.svg
            namespace: hass
            app: hass
            widget:
                type: homeassistant
                url: "http://hass.hass.svc.cluster.local:8123"
                key: "{{HOMEPAGE_VAR_HASS_TOKEN}}"
                custom:
                  - state: sensor.home_electricity_price
                    label: Electricity Price
                  - state: sensor.elec_meter_elec_meter_power
                    label: Electricity Usage    
                  - state: sensor.car_battery_level
                    label: Car Battery
        - ESPHome:
            href: "https://esp.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: ESP32 Controllers
            icon: sh-esphome.svg
            namespace: hass
            app: esphome
            widget:
                type: esphome
                url: http://esphome.hass.svc.cluster.local:6052
        - InfluxDB:
            href: "https://influxb.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: Long Term Statistics
            icon: sh-influxdb.svg
            namespace: hass
            app: influxdb
        - Zigbee:
            href: "https://zigbee.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: Zigbee Controller
            icon: sh-zigbee2mqtt.svg
            namespace: hass
            app: zigbee2mqtt
        - ZWave:
            href: "https://zwave.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: ZWave Controller
            icon: sh-z-wave-js-ui.svg
            namespace: hass
            app: zwavejs
        - Mosquitto:
            description: MQTT Broker
            icon: sh-mosquitto.svg
            namespace: hass
            app: mqtt
    - Infrastructure & Monitoring:
        - ArgoCD:
            href: "https://argocd.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: Kubernetes GitOps
            icon: sh-argo-cd.svg
            namespace: argocd
            app: argocd-server
            widget:
              type: argocd
              url: http://argocd-server.argocd.svc.cluster.local:80
              key: "{{HOMEPAGE_VAR_ARGOCD_TOKEN}}"
        - Portainer:
            href: "https://portainer.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: Container Management
            icon: sh-portainer.svg
            widget:
              type: portainer
              url: "https://portainer.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
              key: "{{HOMEPAGE_VAR_PORTAINER_TOKEN}}"
        - Webnut:
            href: "https://nut.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: UPS Monitoring
            icon: sh-nutalert.svg
        - Unifi:
            href: "https://unifi.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: Unifi Network
            icon: sh-ubiquiti-unifi.svg
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: false
          cpu: false
          memory: false
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: brave
        target: _blank
  docker.yaml: ""
