apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    traefik: false
    ingress: true 
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - Home Automation:
        - Home Assistant:
            href: "https://assistant.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: Home Automation Hub
            icon: sh-home-assistant.svg
            namespace: hass
            app: hass
            widget:
              type: homeassistant
              url: "http://hass.hass.svc.cluster.local:8123"
              key: "{{HOMEPAGE_VAR_HASS_TOKEN}}"
        - ESPHome:
            href: "https://esp.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: ESP32 Controllers
            icon: sh-esphome.svg
            widget:
              type: esphome
              url: http://esphome.hass.svc.cluster.local:6052
        - InfluxDB:
            href: "https://influxb.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: Long Term Statistics
            icon: sh-influxdb.svg
        - Zigbee:
            href: "https://zigbee.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: Zigbee Controller
            icon: sh-zigbee2mqtt.svg
        - ZWave:
            href: "https://zwave.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: ZWave Controller
            icon: sh-z-wave-js-ui.svg
        - Mosquitto:
            description: MQTT Broker
            icon: sh-mosquitto.svg
            namespace: hass
            app: mqtt
    - Tools:
        - AI Chat:
            href: "https://ai.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: AI Chat
            icon: sh-open-webui.svg
        - Planka:
            href: "https://plan.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: Planning Board
            icon: sh-planka.svg
        - Grafana:
            href: "https://grafana.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: Dashboards
            icon: sh-grafana.svg
        - Container Registry:
            href: "https://dockerui.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: Container Registry
            icon: sh-docker.svg
    - Platform and Monitoring:
        - ArgoCD:
            href: "https://argocd.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: Kubernetes GitOps
            icon: sh-argocd.svg
            widget:
              type: argocd
              url: http://argocd-server.argocd.svc.cluster.local:80
              key: "{{HOMEPAGE_VAR_ARGOCD_TOKEN}}"
        - Uptime Kuma:
            href: "https://uptime{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: Uptime Monitoring
            icon: sh-uptime-kuma.svg
        - Portainer:
            href: "https://portainer.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: Container Management
            icon: sh-portainer.svg
        - Webnut:
            href: "https://nut.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: UPS Monitoring
            icon: sh-nutalert.svg
        - Unifi:
            href: "https://unifi.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: Unifi Network
            icon: sh-ubiquiti-unifi.svg
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: brave
        target: _blank
  docker.yaml: ""
