apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    traefik: true
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - Home Automation:
        - Home Assistant:
            href: "https://assistant.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: Home Automation Hub
            icon: sh-home-assistant.svg
            widget:
              type: homeassistant
              url: "http://hass.hass.svc.cluster.local:8123"
              key: "{{HOMEPAGE_VAR_HASS_TOKEN}}"
        - ESPHome:
            href: "https://esp.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: ESP32 Controllers
            icon: sh-esphome.svg
            widget:
              type: esphome
              url: http://esphome.hass.svc.cluster.local:6052
        - InfluxDB:
            href: "https://influxb.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: Long Term Statistics
            icon: sh-influxdb.svg
        - Grafana:
            href: "https://grafana.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: Dashboards
            icon: sh-grafana.svg
        - Zigbee:
            href: "https://zigbee.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: Zigbee Controller
            icon: sh-zigbee2mqtt.svg
        - ZWave:
            href: "https://zwave.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: ZWave Controller
            icon: sh-z-wave-js-ui.svg
        - Mosquitto:
            description: MQTT Broker
            icon: sh-mosquitto.svg
    - Tools:
        - Planka:
            href: "https://plan.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: Planning Board
            icon: sh-planka.svg
    - Platform and Monitoring:
        - ArgoCD:
            href: "https://argocd.{{HOMEPAGE_VAR_BASE_DOMAIN}}"
            description: Kubernetes GitOps
            icon: sh-argocd.svg
            widget:
              type: argo-cd
              url: http://argocd.argocd.svc.cluster.local:80
              key: argocdapikey
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: brave
        target: _blank
  docker.yaml: ""
