apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-auth
  namespace: default
spec:
  forwardAuth:
    address: http://oauth2-proxy.auth.svc.cluster.local:80/oauth2/auth
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-User
      - X-Auth-Request-Email
      - Set-Cookie
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-errors
  namespace: auth
spec:
  errors:
    status:
      - "401"
    service:
      name: oauth2-proxy
      port: 80
    query: "/oauth2/start?rd={url}"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: casdoor-auth
  namespace: default
spec:
  chain:
    middlewares:
    - name: redirect-https
    - name: oauth2-errors@auth@kubernetescrd
    - name: oauth2-auth