apiVersion: traefik.io/v1alpha1
kind: MiddlewareTCP
metadata:
  name: address-whitelist
  namespace: default
spec:
  ipAllowList:
    sourceRange:
      - 192.168.0.9
      - 192.168.0.10
      - 192.168.0.16