resources:
  - ns.yaml
  - ollama/deploy.yaml
  - ollama/ingress.yaml
  - ollama/pvc.yaml
  - ollama/svc.yaml
  - openwebui/
  - pvc.yaml
  - qdrant.yaml
  - searxng/deploy.yaml
  - searxng/ingress.yaml
  - searxng/pvc.yaml
  - searxng/svc.yaml
  - tika/deploy.yaml
  - tika/svc.yaml
  - tika/hpa.yaml