resources:
  - ns.yaml
  - ingress.yaml
  - ollama.yaml
  - openwebui-deploy.yaml
  - openwebui-hpa.yaml
  - openwebui-ingress.yaml
  - openwebui-svc.yaml
  - pvc.yaml
  - qdrant.yaml
  - searxng.yaml
  - tika.yaml