apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-settings
  namespace: ai
data:
  settings.yml: |
    use_default_settings: true

    server:
      bind_address: 0.0.0.0
      port: 8080

    system:
      logging:
        level: info

  limiter.toml: |
    [general]
    enabled = true

    [botdetection.ip_rate]
    limit = 15
    window = 60