apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-settings
  namespace: ai
data:
  settings.yml: |
    use_default_settings: true

    general:
      debug: false
      instance_name: "SearXNG"

    search:
      safe_search: 2
      autocomplete: 'duckduckgo'
      formats:
        - html

    server:
      secret_key: "ultrasecretkey"
      limiter: false
      image_proxy: true

  limiter.toml: |
    [general]
    enabled = true

    [botdetection.ip_rate]
    limit = 15
    window = 60