apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-settings
  namespace: ai
data:
  settings.yml: |
    use_default_settings: true
    server:
      secret_key: "temp-test-key" 
      limiter: false
      image_proxy: true
      port: 8080
      bind_address: "0.0.0.0"
    ui:
      static_use_hash: true
    search:
      safe_search: 0
      autocomplete: ""
      default_lang: ""
      formats:
        - html
        - json

  limiter.toml: |
    [general]
    enabled = true

    [botdetection.ip_rate]
    limit = 15
    window = 60