apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: container-registry
  namespace: default
  annotations:
    #cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: mydomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: container-registry
                port:
                  number: 5000
  tls:
    - secretName: tls-certificate
      hosts:
        - mydomain.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: ui-container-registry
  annotations:
    #cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: mydomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui-container-registry
                port:
                  number: 80
  tls:
    - secretName: tls-certificate
      hosts:
        - mydomain.com
