apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zwavejs
  namespace: hass
  labels:
    app.kubernetes.io/name: zwavejs
  annotations:
    #cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: ZWave Controller
    gethomepage.dev/group: Home Automation
    gethomepage.dev/name: ZWave
    gethomepage.dev/widget.url: https://mydomain.com
spec:
  ingressClassName: traefik
  rules:
    - host: mydomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zwavejs
                port:
                  number: 8091
  tls:
    - secretName: tls-certificate
      hosts:
        - mydomain.com
