apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: vector-udp
  namespace: monitoring
  labels:
    app.kubernetes.io/component: ingest
    app.kubernetes.io/part-of: logging
    app.kubernetes.io/name: vector
spec:
  entryPoints:
    - udp-logs
  routes:
    - services:
        - name: vector-udp
          port: 5140
