apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: influxdb
  namespace: hass
  labels:
    app.kubernetes.io/name: influxdb
  annotations:
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Long Term Statistics
    gethomepage.dev/group: Home Automation
    gethomepage.dev/icon: si-influxdb
    gethomepage.dev/name: InfluxDB
    gethomepage.dev/widget.url: https://mydomain.com
spec:
  ingressClassName: traefik
  rules:
    - host: https://mydomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: influxdb
                port:
                  number: 8086
  tls:
    - secretName: tls-certificate
      hosts:
        - https://mydomain.com
