apiVersion: apps/v1
kind: Deployment
metadata:
  name: casdoor
  namespace: common
  labels:
    app: casdoor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: casdoor
  template:
    metadata:
      labels:
        app: casdoor
    spec:
      containers:
        - name: casdoor
          image: casbin/casdoor:2.270.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: dbName 
              value: casdoor
            - name: driverName
              value: postgres
            - name: dataSourceName 
              valueFrom:
                secretKeyRef:
                  name: casdoor
                  key: dataSourceName
            - name: RUNNING_IN_DOCKER
              value: "true"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          #volumeMounts:
            #- mountPath: /init_data.json
            #  name: casdoor-init
            #  subPath: init_data.json
            #- mountPath: /conf/app.conf
            #  name: casdoor-conf
            #  subPath: app.conf
      volumes:
        - configMap:
            name: casdoor
          name: casdoor-conf
        #- configMap:
        #    name: casdoor-init
        #  name: casdoor-init