apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hass
  namespace: hass
  labels:
    app.kubernetes.io/name: hass
  annotations:
    #cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Home Automation Hub
    gethomepage.dev/group: Home Automation
    gethomepage.dev/name: Home Assitant
    gethomepage.dev/icon: si-homeassistant
    gethomepage.dev/widget.type: homeassistant
    gethomepage.dev/widget.url: https://mydomain.com
    gethomepage.dev/widget.key: replaceme
spec:
  ingressClassName: traefik
  rules:
    - host: https://mydomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hass
                port:
                  number: 8123
  tls:
    - secretName: tls-certificate
      hosts:
        - https://mydomain.com
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: hass
  namespace: hass
spec:
  entryPoints:
    - sonos
  routes:
  - match: HostSNI(`*`)
    services:
    - name: hass
      port: 1400
      nativeLB: true
