apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: common
  labels:
    app.kubernetes.io/name: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: uptime-kuma
  template:
    metadata:
      labels:
        app.kubernetes.io/name: uptime-kuma
    spec:
      containers:
        - name: uptime-kuma
          image: louislam/uptime-kuma:1.23.17-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          volumeMounts:
            # Test without PVC
            #- name: uptime-kuma-pvc
            #  mountPath: /app/data
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        #- name: uptime-kuma-pvc
        #  persistentVolumeClaim:
        #    claimName: kuma
        - name: localtime
          hostPath:
            path: /etc/localtime
