apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma
  namespace: common
  labels:
    app.kubernetes.io/name: uptime-kuma
  annotations:
    #cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Dashboards
    gethomepage.dev/group: Monitoring
    gethomepage.dev/name: Uptime Kuma
    gethomepage.dev/icon: si-uptimekuma
    gethomepage.dev/widget.type: uptimekuma
    gethomepage.dev/widget.url: https://uptime.$DOMAIN_NAME
spec:
  ingressClassName: traefik
  rules:
    - host: uptime.$DOMAIN_NAME
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uptime-kuma
                port:
                  number: 3001
  tls:
    - secretName: tls-certificate
      hosts:
        - uptime.$DOMAIN_NAME
